# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Lucas Lunardi
title: Data Engineer
email: lr.lunardi@unesp.br
# email_title: Email (Email title override)
# phone_title: Phone (Phone title override)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  lureba
linkedin_username: lrlunardi

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Data Engineer specialized in robust pipelines and scalable analytical architectures.
  
  I work on developing and maintaining data pipelines with focus on ETL/ELT processes, 
  data modeling, and analytical architecture. I primarily use SQL, PySpark, and Airflow 
  to organize and deliver data efficiently for analytics and product teams.
  
  **Core Expertise:**
  - Data pipelines (ETL/ELT) with PySpark and Airflow
  - Data modeling and architecture design
  - Cloud Computing and containerization (Docker)
  - Vector databases and multi-agent systems
  - DLT pipelines and Databricks Asset Bundles
  
  Focused on building data infrastructures that scale with business growth and 
  enable data-driven decision making.
content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: ENEM Data Analysis
        link: https://github.com/lureba/ENEM-EDA-EN-US
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/lureba/ENEM-EDA-EN-US
          - title: Python Project
            icon: fab fa-python
            url: https://github.com/lureba/ENEM-EDA-EN-US
        quote: >
          Comprehensive socio-economic analysis of Brazil's national exam using large-scale data processing
        description: |
          **Tags:** `Data Analysis` `Statistical Analysis` `Socio-Economic Research`
          
          Analysis of ENEM (Brazil's National High School Exam) data, processing over **1GB of student records** 
          to explore relationships between educational performance and socio-economic factors.
          
          **Analysis Areas:**
          - Correlation between socio-economic profile and exam scores
          - Geographic performance distribution across Brazilian regions
          - Statistical relationships between family income and academic achievement
          - Educational inequality patterns across different demographics
          
          **Technical Implementation:**
          - Large-scale data processing and cleaning with Pandas
          - Memory-efficient handling of 1GB+ datasets
          - Statistical analysis and data visualization
          - Exploratory data analysis of complex educational datasets

  - title: Experience
    layout: list
    content:
      - layout: right
        title: iFood
        sub_title: Analytics Engineer Intern
        caption: 2025 - Present
        link: https://www.ifood.com.br
        quote: >
          Building scalable data products and modernizing data infrastructure at Latin America's leading food delivery platform
        description: | # this will include new lines to allow paragraphs
          **Data Products & Pipeline Development:**
          - Created robust data products using PySpark and Airflow for large-scale data processing
          - Refactored critical Zendesk → Salesforce data pipeline improving reliability and performance
          - Implemented Kafka topic ingestion for real-time data streaming
          
          **AI Engineering Solutions:**
          - Developed multi-agent system with vector search capabilities for intelligent pipeline refactoring and optimization
          - Implemented vector database integration for semantic similarity matching in data lineage analysis
          - Built comprehensive data monitoring and alerting system with Slack integration for proactive pipeline health tracking
          - Created LLM-powered taxonomy inference system with vector embeddings for ML item classification based on descriptions
          - Developed LLM scripts for automatic domain documentation, generating comprehensive technical documentation across data systems
          - Utilized Docker and LocalStack for cost-effective development and testing of data infrastructure components
          
          **Data Engineering & Architecture:**
          - Designed modular pipeline architecture using Databricks Asset Bundles for improved code maintainability
          - Implemented Real-Time (RT) and Delta Live Tables (DLT) for efficient data processing workflows
          - Structured initial source architecture patterns for consistent data ingestion across multiple systems
          - Created reusable data merge and data quality module utilized across the entire domain



      - layout: right
        title: Yooga (Local Business)
        sub_title: Administrative Assistant
        caption: 2022 - 2023
        quote: >
          Business operations optimization through data-driven insights and process automation
        description: | # this will include new lines to allow paragraphs
          **Business Intelligence & Reporting:**
          - Consolidated fragmented business data to enable comprehensive performance tracking
          - Created automated reporting system for daily sales monitoring and inventory management
          - Developed KPI dashboards tracking key business metrics: daily revenue, average ticket, and cash flow
          
          **Process Optimization:**
          - Streamlined inventory cycle monitoring reducing stockouts and overstock situations
          - Automated manual reporting processes saving 10+ hours weekly of administrative work
          - Established data-driven decision making framework for business operations
          
          **Technical Implementation:**
          - Built end-to-end data pipeline from Excel sources to interactive Power BI dashboards
          - Implemented PostgreSQL database solution for centralized business data storage
          
          This role provided valuable experience in translating business requirements into 
          technical solutions and understanding the impact of data quality on business decisions.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: UNESP - Universidade Estadual Paulista "Júlio de Mesquita Filho"
        sub_title: Bachelor's Degree in Physics
        caption: 2023 - 2026
        quote: >
          Solid foundation in mathematical and computational methods
        description: | # this will include new lines to allow paragraphs
          Comprehensive education in physics with strong emphasis on computational methods and data analysis:
          
          **Key Areas:**
          - Advanced Statistics and Calculus
          - Programming and Software Development
          - Econophysics with Machine Learning applications
          - Experimental Physics and Linear Regression analysis
          - Mathematical modeling and data interpretation

      - layout: top-right
        title: Carlos Augusto Patrício Amorim (COTEC/CTIG)
        sub_title: Technical Degree in Electronics
        caption: 2020 - 2022
        quote: >
          Industrial-focused technical education.
        description: | # this will include new lines to allow paragraphs
          Technical education in electronics with strong focus on industrial applications and programming:
          
          **Programming & Development:**
          - C and Assembly programming
          - Microcontroller programming and embedded systems
          - Arduino project development and prototyping
          
          **Industrial Applications:**
          - Industrial Automation and Robotics
          - CNC programming and operation
          - Control systems and process automation

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
